services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autoalert-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "AutoAlert123*Seguro"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoalert-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SQLConnectionString: "Server=db,1433;Database=AutoAlertDB;User Id=sa;Password=AutoAlert123*Seguro;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./Codigo/AutoAlertFrontend
      dockerfile: Dockerfile
    container_name: autoalert-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlserver_data: